version: '3.3'

services:
  postgres:
    build: .
    container_name: postgres-with-logs
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: library
    restart: always